In [103]:
import pandas as pd
import numpy as np
import math

#### Solve The System of Three Linear Equations With Three Unknowns:

- 2x1 - x2 + x3 = 8
- x1 + 2x2 + 3x3 = 9
- 3x1 + 0x2 + -1x3 = 3

Ax = C

In [104]:
a = np.array

In [112]:
# Coefficient Matrix

A = a([[2,-1,1]
      ,[1,2,3]
      ,[3,0,-1]])

A

array([[ 2, -1,  1],
       [ 1,  2,  3],
       [ 3,  0, -1]])

In [114]:
# Constant Matrix

C = a([[8.0]
      ,[9.0]
      ,[3.0]])
C

array([[8.],
       [9.],
       [3.]])

In [107]:
np.linalg.det(A)

-19.999999999999996

In [108]:
# Unknown variable matrix

x = np.dot(np.linalg.inv(A),C)
x

array([[ 2.],
       [-1.],
       [ 3.]])

In [71]:
np.linalg.inv(A)[0] * C.reshape(1,-1)

array([[0.8 , 0.45, 0.75]])

In [72]:
(np.linalg.inv(A)[0] * C.reshape(1,-1)).sum(axis=1)

array([2.])

Ax = C

In [73]:
x.reshape(1,-1) * A

array([[ 4.,  1.,  3.],
       [ 2., -2.,  9.],
       [ 6., -0., -3.]])

In [74]:
(x.reshape(1,-1) * A).sum(axis=1).reshape(-1,1)

array([[8.],
       [9.],
       [3.]])

In [75]:
np.dot(A,x)

array([[8.],
       [9.],
       [3.]])

In [76]:
# Multiplicative Inverse

np.linalg.inv(A)

array([[ 0.1 ,  0.05,  0.25],
       [-0.5 ,  0.25,  0.25],
       [ 0.3 ,  0.15, -0.25]])

In [77]:
# The dot product of the coefficient matrix and its multiplicative inverse is the:
# Identity Matrix (eye)

(np.dot(np.linalg.inv(A),A)).round(0) 

array([[ 1.,  0.,  0.],
       [-0.,  1., -0.],
       [ 0.,  0.,  1.]])

In [78]:
np.eye(A.shape[0])

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Solve The System of Three Linear Equations With Three Unknowns:

- (- 1x1) - 2x2 + 3x3 = -30
- (- 2x1) - 3x2 - 5x3 = 22
- 1x1 + 5x2 + 5x3 = -11

- Ax = C
- dot(A^-1,C) = x
- dot(A,x) = C

In [79]:
A = a([[-1,-2,3]
      ,[-2,-3,-5]
      ,[1,5,5]])

C = [[-30]
    ,[22]
    ,[-11]]

In [80]:
np.linalg.det(A)

-41.00000000000001

In [81]:
x = np.dot(np.linalg.inv(A),C)
x

array([[-1.],
       [ 5.],
       [-7.]])

In [82]:
np.dot(A,x)

array([[-30.],
       [ 22.],
       [-11.]])

# No Solution

#### Solve The System of Three Linear Equations With Three Unknowns:

- (- 3x1) - 9x2 - 3x3 = 24
- 1x1 - 3x2 + 11x3 = -2
- (-2x1) + 5x2 -20x3 = -5

In [83]:
A = a([[-3,-9,3]
      ,[1,-3,11]
      ,[-2,5,-20]])

C = [[24]
    ,[-2]
    ,[-5]]

In [84]:
np.linalg.det(A)

0.0

In [85]:
np.linalg.inv(A)

LinAlgError: Singular matrix

# Infinite Soutions


#### Solve The System of Four Linear Equations With Four Unknowns:

- 1x1 + 2x2 - 3x3 + 7x4 = 4
- 3x1 - 1x2  -2x3 + 0x4 = 12
- (-2x1) + 5x2 + 0x3 +2x4 = 5
- 2x1 + 3x2 -5x3 + 11x4= 8

In [86]:
A = a([[1,2,-3,7]
      ,[3,-1,-2,0]
      ,[-2,5,0,2]
      ,[2,3,-5,11]])

C = [[4]
    ,[12]
    ,[5]
    ,[8]]

In [87]:
np.linalg.det(A)

0.0

In [88]:
np.linalg.inv(A)

LinAlgError: Singular matrix

### Conclusion

- The dot product of the multiplicative inverse of a coefficient matrix and the constants in regards to a system of linear equations will solve for variables in the system